//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamiahsalafiyah.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JAMAIAHSALAFIYAH_HOUSTONEntities : DbContext
    {
        public JAMAIAHSALAFIYAH_HOUSTONEntities()
            : base("name=JAMAIAHSALAFIYAH_HOUSTONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyForm> CompanyForm { get; set; }
        public virtual DbSet<CompanyModule> CompanyModule { get; set; }
        public virtual DbSet<Forms> Forms { get; set; }
        public virtual DbSet<ImageFile> ImageFile { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<StaffList> StaffList { get; set; }
        public virtual DbSet<Usergroup> Usergroup { get; set; }
        public virtual DbSet<UserGroupForm> UserGroupForm { get; set; }
        public virtual DbSet<UserGroupModule> UserGroupModule { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<SessionYear> SessionYear { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<TutionFeeType> TutionFeeType { get; set; }
        public virtual DbSet<SessionMonth> SessionMonth { get; set; }
        public virtual DbSet<MonthlyTutionFee> MonthlyTutionFee { get; set; }
    }
}
