//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamiahsalafiyah.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyTutionFee
    {
        public int Id { get; set; }
        public Nullable<int> SessionYearId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SessionMonthId { get; set; }
        public Nullable<int> ResidentTypeId { get; set; }
        public Nullable<int> TutionFeeTypeId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ResidentType ResidentType { get; set; }
        public virtual SessionMonth SessionMonth { get; set; }
        public virtual SessionYear SessionYear { get; set; }
        public virtual TutionFeeType TutionFeeType { get; set; }
    }
}
