//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamiahsalafiyah.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfoPreviousInstitution
    {
        public int Id { get; set; }
        public Nullable<int> StudentInfo_FK { get; set; }
        public string ExamName { get; set; }
        public string ExamYear { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionCode { get; set; }
        public string InstitutionDistrict { get; set; }
        public string RegiNo { get; set; }
        public string RollNo { get; set; }
        public string Grade { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
