//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamiahsalafiyah.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssigned
    {
        public int Id { get; set; }
        public Nullable<int> StudentInfo_FK { get; set; }
        public Nullable<int> Department_FK { get; set; }
        public Nullable<int> ResidentType_FK { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ResidentType ResidentType { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
