//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamiahsalafiyah.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInfo()
        {
            this.StudentInfoPreviousInstitution = new HashSet<StudentInfoPreviousInstitution>();
            this.StudentAttachFile = new HashSet<StudentAttachFile>();
        }
    
        public int Id { get; set; }
        public byte[] StudentPhoto { get; set; }
        public string StudentNameBangla { get; set; }
        public string StudentNameEnglish { get; set; }
        public string StudentNameArabic { get; set; }
        public Nullable<System.DateTime> StudentDateOfBirth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Nationality { get; set; }
        public string FatherNameBangla { get; set; }
        public string FatherNameEnglish { get; set; }
        public Nullable<bool> FatherIsAlive { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherMobile { get; set; }
        public string MotherNameBangla { get; set; }
        public string MotherNameEnglish { get; set; }
        public Nullable<bool> MotherIsAlive { get; set; }
        public string MotherMobile { get; set; }
        public string GuardianName { get; set; }
        public string GuardianOccupation { get; set; }
        public string GuardianHouseNo { get; set; }
        public string GuardianVillage { get; set; }
        public string GuardianPostOffice { get; set; }
        public string GuardianThana { get; set; }
        public string GuardianDistrict { get; set; }
        public string RelationWithGuardian { get; set; }
        public Nullable<int> YearlyIncomeGuardian { get; set; }
        public string PermanentAddressHouse { get; set; }
        public string PermanentAddressVillage { get; set; }
        public string PermanentAddressPostOffice { get; set; }
        public string PermanentAddressThana { get; set; }
        public string PermanentAddressDistrict { get; set; }
        public string HonarablePersonNameInArea { get; set; }
        public string PreviousInstitutionName { get; set; }
        public string PreviousInstitutionAddress { get; set; }
        public string PreviousInstitutionClass { get; set; }
        public string PreviousInstitutionClearanceNo { get; set; }
        public Nullable<System.DateTime> PreviousInstitutionClearanceDate { get; set; }
        public Nullable<int> AdmittedDepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInfoPreviousInstitution> StudentInfoPreviousInstitution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttachFile> StudentAttachFile { get; set; }
    }
}
